name: Deno

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - uses: actions/checkout@v1

      - id: deno_hello
        run: |
          deno --version
          echo "::set-output name=hello::$(deno run hello.ts)"

      - run: echo ${{ steps.deno_hello.outputs.hello }}
