name: Output

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Output
        run: echo "::set-output name=hello::hello world"

      - name: Get Output
        run: echo ${{ steps.api.outputs.hello }}
