name: Output

on:
  push:

jobs:
  output:
    runs-on: ubuntu-latest
    # outputs:
    #  month: ${{ steps.foo.outputs.hello }}

    steps:
      - name: Set Output
        id: foo
        run: echo "::set-output name=hello::$(date +%s)"

      - name: Get Output
        run: echo ${{ steps.foo.outputs.hello }}
