name: Output

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      month: ${{ steps.foo.outputs.hello }}

    steps:
      #- name: Checkout
      #  uses: actions/checkout@v1

      - name: Set Output
        id: foo
        run: echo "::set-output name=hello::hello world"

      - name: Get Output
        run: echo ${{ steps.foo.outputs.hello }}
